### ISSUE TITLE
Split dist/esm in multiple files

### ISSUE THREAD

**Issue by romgrk** [amoutonbrady/rollup-preset-solid#1]
It seems that this preset bundles all files into a single `dist/esm/index.js`. Is it possible to keep it in multiple files?

**Comment by amoutonbrady** [comment]
Hey, sorry for the delay... I'm definitely not the best at keeping up with issues across the board.

What do you mean "keep it in multiple files"? I'm pretty sure that if you use code splitting via `import('./my-module.js')` it should split it into different files but that might not be what you ahve in mind.

**Comment by amoutonbrady** [comment]
I feel like this issue has run its course. Feel free to reopen if needed :)
