### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by StJohn3D** [amoutonbrady/rollup-preset-solid#4]
I really want to use this but can't legally unless it includes a license, preferably MIT

**Comment by amoutonbrady** [comment]
It was kind of implied in the `package.json` file with the `license` key. I just added the license explicitly to the repo. Hope it helps :)

**Comment by StJohn3D** [comment]
Oh thank you! I didn't think to check the package.json file itself. I'm in the habit of looking here in a GitHub repo 
![image](https://user-images.githubusercontent.com/7581439/149642224-c05d6a45-1b85-492e-8d6c-1ca45ce8aa90.png)
