### ISSUE TITLE
Override `input` and `output`

### ISSUE THREAD

**Issue by mosheduminer** [amoutonbrady/rollup-preset-solid#5]
Currently, the source in package.json [takes precedence](https://github.com/amoutonbrady/rollup-preset-solid/blob/f2d5a531dbf909b8153f3e674b599b499e3889d8/src/index.ts#L32) over the `input` option. Additionally, it seems the output option is ignored entirely. Can we please change this, so that input/output can be overriden?

**Comment by amoutonbrady** [comment]
Absolutely! Let me have a look

**Comment by amoutonbrady** [comment]
This should be fixed in `1.1.0`. Let me know if that works for you!
